### Recuperar todas las películas
GET http://localhost:1234/movies

### Recuperar una película por id
GET http://localhost:1234/movies/f227d46b-b564-4f48-867c-effe14f39008

### Recuperar todas las películas por un género
GET http://localhost:1234/movies?genre=ACTION


### Crear una película
POST http://localhost:1234/movies
Content-Type: application/json

{
"title": "The Dark Knight7",
"year": 1979,
"director": "Christopher Nolan",
"duration": 152,
"poster": "https://i.ebayimg.com/images/g/yokAAOSw8w1YARbm/s-l1200.jpg",
"genre": [
        "Action"
    ]
}


### Actializar una película
PATCH http://localhost:1234/movies/f227d46b-b564-4f48-867c-effe14f39008
Content-Type: application/json

{
    "year": 1994
}